### ISSUE TITLE
upgrade bisheng

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/bisheng-plugin-antd#4]
- https://github.com/ant-design/bisheng-plugin-antd/blob/master/package.json#L62
- https://github.com/ant-design/ant-design-mobile/commit/327cd8a802412fa2099ce8461c4c92e41565d0b4

which cause warning

**Comment by paranoidjk** [comment]
@benjycui

**Comment by benjycui** [comment]
Just PR

**Comment by paranoidjk** [comment]
我好像没这个库的权限...

**Comment by benjycui** [comment]
ant-design group 下面的你都有权限 commit

只是发布权限在我这里而已。

**Comment by paranoidjk** [comment]
@benjycui 刚push了，是没权限，因为之前我发现没权限处理这个库的issue，你check下？

**Comment by benjycui** [comment]
现在应该 OK 了。
